alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'aesgroupalfa@gmail.com'
      smtp_auth_username: 'aesgroupalfa@gmail.com'
      smtp_auth_password: 'abcd efgh ijkl mnop'   # please dont commit real password to git, use secrets instead
      smtp_require_tls: true
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 10s
      receiver: 'blackhole' # 1. The default route is now a true black hole
      routes:
        - matchers:
            - namespace="default" # 2. BUT, if the alert is from our apps...
          receiver: 'email-receiver' # 3. ...route it to the email inbox!
    receivers:
      - name: 'blackhole'
        # Notice there is no email config here. Alerts sent here simply vanish.
      - name: 'email-receiver'
        email_configs:
          - to: 'kbneyo55@gmail.com'
            send_resolved: true