alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'aesgroupalfa@gmail.com'
      smtp_auth_username: 'aesgroupalfa@gmail.com'
      smtp_auth_password: 'xuxz eoyb qglq atlc' # Do not include spaces
      smtp_require_tls: true
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 10s # Fast wait time for testing
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email-receiver'
    receivers:
      - name: 'email-receiver'
        email_configs:
          - to: 'kbneyo55@gmail.com'
            send_resolved: true