alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'aesgroupalfa@gmail.com'
      smtp_auth_username: 'aesgroupalfa@gmail.com'
      smtp_auth_password: 'xuxz eoyb qglq atlc'
      smtp_require_tls: true
    route:
      receiver: 'null' # We tell the route to use the null receiver
    receivers:
      - name: 'null'   # But we hijack the 'null' receiver to be your email!
        email_configs:
          - to: 'kbneyo55@gmail.com'
            send_resolved: true